[package]
name = "libscanmem"
version.workspace = true
edition.workspace = true
license = "LGPL-3.0-or-later"
homepage.workspace = true
description = "Process attach, memory scanning/matching engine, and memory read/write for scanmem-rs"
keywords.workspace = true
repository.workspace = true

[features]
default = []
